### ISSUE TITLE
Suggestion after reading http://www.ziaconsulting.com/blog/alfresco-help-simplifying-extension-development/

### ISSUE THREAD

**Issue by douglascrp** [binduwavell/alf-dev-helper#3]
Hello @binduwavell 
While reading your blog post at http://www.ziaconsulting.com/blog/alfresco-help-simplifying-extension-development/, I saw the sentence below

> My plan for this project is to include simple extensions to the platform and share those that will be most useful for developers. I would not expect this module to be deployed to production.

I have to disagree with you.
Why not to use an "isAdmin" evaluator, just like js-console does, and allow us to install this addon on production?
I haven't checked the code yet to see if this is already in place or not, anyways, this is my suggestion.

Your idea is awesome.

**Comment by binduwavell** [comment]
@douglascrp I’m so sorry I missed this 6 months ago! I haven’t coded on alfdevhelper in over 6 months, so let me take a look. I think there was a reason not to deploy to prod. But if not, the isAdmin evaluator seems like a reasonable approach.

**Comment by douglascrp** [comment]
@binduwavell To be honest, I didn't even remember about this project, but I have tothank you for remembering about it, because yesterday I was searching for a way to implement the open in node browser action by myself :D

I am building this project right now and deploying in one of my dev servers.

**Comment by binduwavell** [comment]
@douglascrp and I were discussing this on Skype. I think the right thing to do is:

Create a module component that bootstraps an ALFRESCO_DEVELOPERS group if one does not exists.

If the group is created by us, then (and only then), ALFRESCO_ADMINISTRATORS will be added to the group.

Then UI actions can be only enabled for members of ALFRESCO_DEVELOPERS. Also any server side features we add can be limited to this group.

**Comment by binduwavell** [comment]
Would be nice if: https://github.com/binduwavell/generator-alfresco/issues/84 was done...

**Comment by binduwavell** [comment]
Version 1.0.1 of developer helper bootstraps the ALFRESCO_DEVELOPERS group if it doesn't already exist. If it creates the group it adds ALFRESCO_ADMINISTRATORS to the group. The UI customizations are then limited to members of ALFRESCO_DEVELOPERS. Additionally I updated the Open in Node Browser action to only be available for admins as node browser is only available to administrators.
