### ISSUE TITLE
AssertionError: Trying to copy from a source that does not exist: ... node_modules/generator-alfresco/generators/app/templates/.gitignore

### ISSUE THREAD

**Issue by hseritt** [binduwavell/alf-dev-helper#4]
Hi Bindu,

I was hoping to give your alf-dev-helper a whirl this morning. I was able to get yo installed properly after completely re-doing my node install. Btw, I'm using node --version: 6.9.4 which uses npm --version: 3.10.10 (let me know if those are not compatible with your project).

At any rate, I ran:

`# yo alfresco
`

and encountered this message:

```
You don’t seem to have a generator with the name “alfresco” installed.

Install them with npm install generator-alfresco.
```

So naturally, I tried:

`# npm install generator-alfresco
`

I got a warning after install:

```
npm WARN enoent ENOENT: no such file or directory, open '/media/hseritt/Disk1/Devel/projects/tests/YoAlfresco/package.json'
npm WARN YoAlfresco No description
npm WARN YoAlfresco No repository field.
npm WARN YoAlfresco No README data
npm WARN YoAlfresco No license field.
```

And it seemed to be installed correctly:

```
# npm ls | grep alfresco
└─┬ generator-alfresco@0.0.2
```

But when I then tried to run yo alfresco I get this:

```
$ yo alfresco

? Name of the project YoAlfresco
? Description of the project 
? Enter the groupId com.example
? Enter the artifactId YoAlfresco
? Enter the package com.example.yoAlfresco
? Version number 1.0-SNAPSHOT

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /media/hseritt/Disk1/Devel/projects/tests/YoAlfresco/node_modules/generator-alfresco/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/media/hseritt/Disk1/Devel/projects/tests/YoAlfresco/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/media/hseritt/Disk1/Devel/projects/tests/YoAlfresco/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child.writing (/media/hseritt/Disk1/Devel/projects/tests/YoAlfresco/node_modules/generator-alfresco/generators/app/index.js:94:13)
    at /media/hseritt/Disk1/Devel/projects/tests/YoAlfresco/node_modules/yeoman-generator/lib/base.js:430:16
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

It appears to be expecting a .gitignore file in the app/templates/ directory. I checked that path and found a .npmignore file. Having a look at it, I thought it looked like a .gitignore file. So I copied it to .gitignore, went back and re-ran yo alfresco. This time it completed without incident. 

Anyways, hope that's helpful for you.

Thanks,
Harlin

**Comment by binduwavell** [comment]
Per our discussion on Skype. It looks like you installed the other generator-alfresco and not this one. At some point I hope we'll be able to take over that namespace on npm. For now you should run: `npm install -g binduwavell/generator-alfresco`. I will close this issue. If I've misunderstood something feel free to re-open the issue.
