### ISSUE TITLE
Not possible to build the project without fixing the dependencies versions

### ISSUE THREAD

**Issue by douglascrp** [binduwavell/alf-dev-helper#5]
@binduwavell I have just tried to build the project just like it is now, but it is not working.
In order to fix it, it is required to fix the dependencies versions from 1.0.0-SNAPSHOT to 1.0.1-SNAPSHOT, as this is the version set for both repo and share customisation projects, but none of the others use this new version yet.

I guess it worked for you because you had the 1.0.0-SNAPSHOT version in your local repository.

**Comment by binduwavell** [comment]
Makes sense, I’ll get it updated. Thanks again.

**Comment by douglascrp** [comment]
No need. It is fixed now.
